<div id="side">
  <h1><a href="/">HOMEPAGE<br>MANAGER</a><span class="version">ver4.1</span></h1>
  <nav>
    <ul class="menu">
      <li>
        <span class="parent_link">menu title</span>
        <ul class="submenu">
          <li><a href="#">submenu title</a></li>
          <li><a href="#">submenu title</a></li>
          <li><a href="#">submenu title</a></li>
        </ul>
      </li>
      <li><a href="/list.html">リスト一覧</a></li>
      <li><a href="/form.html">登録フォーム</a></li>
    </ul>
  </nav>
</div>
